import {
	BarChart3,
	Bot,
	CalendarClock,
	Headphones,
	HelpCircle,
	Home,
	Link2,
	MessageSquare,
	Package,
	Receipt,
	ShieldCheck,
	ShoppingCart,
	Users,
	Wrench,
} from 'lucide-react';
import type { NavItem } from '@/types/navigation';

export const navItems: NavItem[] = [
	{
		name: 'Home',
		icon: Home,
		href: '/dashboard',
		hasDropdown: false,
		section: 'PRINCIPAL',
	},
	{
		name: 'Produtos',
		icon: Package,
		href: '/products',
		hasDropdown: false,
		section: 'PRINCIPAL',
	},
	{
		name: 'Vendas',
		icon: ShoppingCart,
		href: '/sales',
		hasDropdown: false,
		section: 'PRINCIPAL',
	},
	{
		name: 'Links',
		icon: Link2,
		href: '/links',
		hasDropdown: false,
		section: 'SISTEMA',
	},
	{
		name: 'Financeiro',
		icon: Receipt,
		href: '/fatura',
		hasDropdown: false,
		section: 'PRINCIPAL',
	},
	{
		name: 'Relatórios',
		icon: BarChart3,
		href: '/reports',
		hasDropdown: false,
		section: 'PRINCIPAL',
	},
	{
		name: 'Comunidade',
		icon: MessageSquare,
		href: '/community',
		hasDropdown: false,
		section: 'CONTEUDO',
	},
	{
		name: 'Fórum',
		icon: HelpCircle,
		href: '/forum',
		hasDropdown: false,
		section: 'CONTEUDO',
	},
	{
		name: 'Agendamentos',
		icon: CalendarClock,
		href: '/agendamentos',
		hasDropdown: false,
		section: 'OPERACAO',
	},
	{
		name: 'Suporte',
		icon: Headphones,
		href: '/suporte',
		hasDropdown: false,
		section: 'OPERACAO',
	},
	{
		name: 'OmniResposta',
		icon: Bot,
		href: '/omniresposta',
		hasDropdown: false,
		section: 'OPERACAO',
	},
	{
		name: 'Acessos',
		icon: ShieldCheck,
		href: '/acessos',
		hasDropdown: false,
		section: 'SISTEMA',
	},
	{
		name: 'Alunos',
		icon: Users,
		href: '/alunos',
		hasDropdown: false,
		section: 'CONTEUDO',
	},
	{
		name: 'Ferramentas',
		icon: Wrench,
		href: '/ferramentas/hub',
		hasDropdown: false,
		section: 'FERRAMENTAS',
	},
];
