/**
 * Blocos extras do motor (CAD / Cotação / Estúdio / Export) — espelho do back.
 *
 * Estes 14 blocos são usados pelas tools-mãe publicadas (central_custos,
 * estudio_cad, estudio_ia, estudio_editor, estudio_laser) mas não entraram no
 * `BLOCK_CATALOG` explícito nem no `IMAGR_BLOCKS`. Sem o spec, o builder
 * (tool-builder-view `loadFabrica`) não consegue resolver o id e força a tool
 * pra o modo CÓDIGO — o admin não consegue editar visualmente.
 *
 * Round-trip SEGURO: `buildDoc`/`docToState` preservam TODOS os params verbatim,
 * independentemente do spec (o spec só decide quais params ganham editor visual).
 * Mesmo um spec parcial não corrompe a tool ao salvar — params não listados
 * continuam no pipeline, só não têm campo na UI.
 */

import type { BlockSpec } from './block-catalog';

export const EXTRA_BLOCKS: BlockSpec[] = [
	/* ── CAD / Cotação (quote.ts) ── */
	{
		id: 'cad.parse',
		label: 'Ler DXF/SVG',
		sub: 'Lê o arquivo e devolve o desenho na IR do CAD',
		icon: 'FileSearch',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'file',
				kind: 'ref',
				refType: 'buffer',
				label: 'Arquivo DXF ou SVG',
				hint: 'Input type="file" — o motor põe o buffer cru na bag.',
				required: true,
			},
			{
				name: 'filename',
				kind: 'ref',
				refType: 'string',
				label: 'Nome do arquivo',
				hint: 'Serve só de desempate; o formato é decidido pelo conteúdo.',
			},
			{
				name: 'unit_hint',
				kind: 'literal',
				valueType: 'enum',
				label: 'Unidade declarada',
				hint: 'auto = deixa o arquivo mandar.',
				default: 'auto',
				options: ['auto', 'mm', 'cm', 'm', 'in', 'pol', 'ft', 'px'],
			},
			{
				name: 'tolerance_mm',
				kind: 'literal',
				valueType: 'number',
				label: 'Tolerância de tesselação (mm)',
				default: 0.05,
				min: 0.001,
				max: 1,
				step: 0.001,
			},
		],
		outputs: [
			{ name: 'sketch', type: 'string', label: 'Desenho (sketch IR)' },
			{ name: 'unit', type: 'string', label: 'Unidade detectada' },
			{ name: 'unit_detected', type: 'string', label: 'Origem da unidade' },
			{ name: 'unit_warning', type: 'string', label: 'Aviso de unidade' },
			{ name: 'entity_count', type: 'number', label: 'Entidades lidas' },
			{ name: 'format', type: 'string', label: 'Formato (dxf/svg)' },
			{ name: 'bbox_w_mm', type: 'number', label: 'Largura bbox (mm)' },
			{ name: 'bbox_h_mm', type: 'number', label: 'Altura bbox (mm)' },
			{ name: 'warnings', type: 'string', label: 'Avisos de leitura' },
			{ name: 'json', type: 'string', label: 'Diagnóstico (JSON)' },
		],
	},
	{
		id: 'cad.metrics',
		label: 'Medir geometria',
		sub: 'Comprimento de corte, área, furos e peças — determinístico',
		icon: 'Ruler',
		accent: 'cyan',
		category: 'image',
		params: [
			{
				name: 'sketch',
				kind: 'ref',
				refType: 'string',
				label: 'Desenho (sketch)',
				hint: 'Saída de cad.parse.',
				required: true,
			},
			{
				name: 'tolerance_mm',
				kind: 'literal',
				valueType: 'number',
				label: 'Tolerância de encadeamento (mm)',
				hint: 'Distância máxima entre pontas para juntar contornos.',
				default: 0.05,
				min: 0.001,
				max: 5,
				step: 0.001,
			},
			{
				name: 'eps_mm',
				kind: 'literal',
				valueType: 'number',
				label: 'Tolerância geométrica (mm)',
				default: 0.05,
				min: 0.001,
				max: 1,
				step: 0.001,
			},
		],
		outputs: [
			{ name: 'metrics', type: 'string', label: 'Métricas (objeto)' },
			{ name: 'json', type: 'string', label: 'Métricas (JSON)' },
			{ name: 'length_mm', type: 'number', label: 'Comprimento de corte (mm)' },
			{
				name: 'engrave_length_mm',
				type: 'number',
				label: 'Comprimento de gravação (mm)',
			},
			{ name: 'pieces', type: 'number', label: 'Peças' },
			{ name: 'holes', type: 'number', label: 'Furos' },
			{ name: 'contours', type: 'number', label: 'Contornos' },
			{ name: 'open_contours', type: 'number', label: 'Contornos abertos' },
			{ name: 'pierces', type: 'number', label: 'Piercings' },
			{ name: 'width_mm', type: 'number', label: 'Largura (mm)' },
			{ name: 'height_mm', type: 'number', label: 'Altura (mm)' },
			{ name: 'area_net_mm2', type: 'number', label: 'Área líquida (mm²)' },
			{ name: 'area_gross_mm2', type: 'number', label: 'Área bruta (mm²)' },
			{ name: 'warnings', type: 'string', label: 'Avisos' },
		],
	},
	{
		id: 'cad.diagnose',
		label: 'Diagnosticar arquivo',
		sub: 'Problemas em PT-BR acionável, separados do que vai ao cliente',
		icon: 'ScanLine',
		accent: 'amber',
		category: 'image',
		params: [
			{
				name: 'sketch',
				kind: 'ref',
				refType: 'string',
				label: 'Desenho (sketch)',
				required: true,
			},
			{
				name: 'metrics',
				kind: 'ref',
				refType: 'string',
				label: 'Métricas',
				hint: 'Saída de cad.metrics.',
				required: true,
			},
			{
				name: 'chapa_w',
				kind: 'literal',
				valueType: 'number',
				label: 'Largura da chapa (mm)',
				hint: 'Habilita o teste de peça maior que a chapa.',
				min: 1,
				max: 20000,
			},
			{
				name: 'chapa_h',
				kind: 'literal',
				valueType: 'number',
				label: 'Altura da chapa (mm)',
				min: 1,
				max: 20000,
			},
			{
				name: 'espessura_mm',
				kind: 'literal',
				valueType: 'number',
				label: 'Espessura do material (mm)',
				hint: 'Habilita o teste de furo pequeno demais.',
				min: 0.01,
				max: 100,
			},
		],
		outputs: [
			{ name: 'warnings', type: 'string', label: 'Diagnósticos (objeto)' },
			{
				name: 'public_warnings',
				type: 'string',
				label: 'Diagnósticos públicos',
			},
			{ name: 'json', type: 'string', label: 'Diagnósticos (JSON)' },
			{ name: 'error_count', type: 'number', label: 'Erros' },
			{ name: 'warning_count', type: 'number', label: 'Total de avisos' },
			{ name: 'has_error', type: 'number', label: 'Tem erro impeditivo' },
			{ name: 'codes', type: 'string', label: 'Códigos dos diagnósticos' },
		],
	},
	{
		id: 'cad.preview_svg',
		label: 'Prévia SVG',
		sub: 'Prévia inline na escala real (mm), sem subir para storage',
		icon: 'Shapes',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'sketch',
				kind: 'ref',
				refType: 'string',
				label: 'Desenho (sketch)',
				required: true,
			},
			{
				name: 'fundo',
				kind: 'literal',
				valueType: 'string',
				label: 'Cor de fundo',
				hint: 'Vazio deixa transparente.',
				default: '',
				widget: 'textarea',
			},
		],
		outputs: [
			{ name: 'svg', type: 'string', label: 'SVG (texto)' },
			{ name: 'dataUrl', type: 'string', label: 'SVG (data URL base64)' },
		],
	},
	{
		id: 'quote.price',
		label: 'Orçamento',
		sub: 'Custo e preço de venda — material, tempo, margem e desconto',
		icon: 'Calculator',
		accent: 'emerald',
		category: 'util',
		params: [
			{
				name: 'metrics',
				kind: 'ref',
				refType: 'string',
				label: 'Métricas',
				hint: 'Saída de cad.metrics.',
				required: true,
			},
			{
				name: 'tool',
				kind: 'literal',
				valueType: 'string',
				label: 'Tool dona das coleções',
				default: 'central_custos',
			},
			{
				name: 'qtd',
				kind: 'literal',
				valueType: 'int',
				label: 'Quantidade',
				default: 1,
				min: 1,
				max: 100000,
			},
			{
				name: 'espessura_mm',
				kind: 'literal',
				valueType: 'number',
				label: 'Espessura (mm)',
				required: true,
				min: 0.01,
				max: 100,
			},
			{
				name: 'material_id',
				kind: 'literal',
				valueType: 'string',
				label: 'Material (UUID ou família)',
				hint: 'Id na coleção ou família ("mdf", "aço carbono").',
			},
			{
				name: 'material_nome',
				kind: 'literal',
				valueType: 'string',
				label: 'Nome do material (manual)',
			},
			{
				name: 'material_familia',
				kind: 'literal',
				valueType: 'string',
				label: 'Família (manual)',
			},
			{
				name: 'preco_kg',
				kind: 'literal',
				valueType: 'number',
				label: 'Preço por kg (R$)',
				min: 0,
				max: 100000,
			},
			{
				name: 'preco_m2',
				kind: 'literal',
				valueType: 'number',
				label: 'Preço por m² (R$)',
				min: 0,
				max: 100000,
			},
			{
				name: 'densidade',
				kind: 'literal',
				valueType: 'number',
				label: 'Densidade (g/cm³)',
				min: 0.01,
				max: 25,
			},
			{
				name: 'chapa_w',
				kind: 'literal',
				valueType: 'number',
				label: 'Largura da chapa (mm)',
				min: 1,
				max: 20000,
			},
			{
				name: 'chapa_h',
				kind: 'literal',
				valueType: 'number',
				label: 'Altura da chapa (mm)',
				min: 1,
				max: 20000,
			},
			{
				name: 'custo_fixo_chapa',
				kind: 'literal',
				valueType: 'number',
				label: 'Custo fixo por chapa (R$)',
				min: 0,
				max: 100000,
			},
			{
				name: 'base_area',
				kind: 'literal',
				valueType: 'enum',
				label: 'Base de área',
				default: 'perfil',
				options: ['perfil', 'liquido', 'bbox', 'chapa'],
			},
			{
				name: 'perfil_id',
				kind: 'literal',
				valueType: 'string',
				label: 'Perfil de custo (UUID)',
			},
			{
				name: 'velocidade_mm_s',
				kind: 'literal',
				valueType: 'number',
				label: 'Velocidade de corte (mm/s)',
				hint: 'Override da cascata.',
				min: 0.01,
				max: 20000,
			},
			{
				name: 'passadas',
				kind: 'literal',
				valueType: 'int',
				label: 'Passadas',
				min: 1,
				max: 50,
			},
			{
				name: 'pierce_s',
				kind: 'literal',
				valueType: 'number',
				label: 'Tempo de perfuração (s)',
				min: 0,
				max: 120,
			},
			{
				name: 'velocidades_collection',
				kind: 'literal',
				valueType: 'string',
				label: 'Coleção de velocidades',
				default: 'velocidades',
			},
			{
				name: 'acabamento',
				kind: 'literal',
				valueType: 'number',
				label: 'Acabamento por peça (R$)',
				min: 0,
				max: 100000,
			},
			{
				name: 'tempo_manual_min',
				kind: 'literal',
				valueType: 'number',
				label: 'Tempo manual (min)',
				min: 0,
				max: 10000,
			},
			{
				name: 'desconto_pct',
				kind: 'literal',
				valueType: 'number',
				label: 'Desconto (%)',
				min: 0,
				max: 99,
			},
			{
				name: 'precificar_por',
				kind: 'literal',
				valueType: 'enum',
				label: 'Precificar por',
				default: 'perfil',
				options: ['perfil', 'markup', 'margem'],
			},
		],
		outputs: [
			{ name: 'breakdown', type: 'string', label: 'Detalhamento (objeto)' },
			{ name: 'json', type: 'string', label: 'Detalhamento (JSON)' },
			{ name: 'public', type: 'string', label: 'Orçamento público (objeto)' },
			{
				name: 'public_json',
				type: 'string',
				label: 'Orçamento público (JSON)',
			},
			{
				name: 'price_unit_cents',
				type: 'number',
				label: 'Preço unitário (centavos)',
			},
			{
				name: 'price_total_cents',
				type: 'number',
				label: 'Preço total (centavos)',
			},
			{ name: 'price_unit', type: 'string', label: 'Preço unitário (R$)' },
			{ name: 'price_total', type: 'string', label: 'Preço total (R$)' },
			{
				name: 'cost_unit_cents',
				type: 'number',
				label: 'Custo unitário (centavos)',
			},
			{ name: 'lead_time_days', type: 'number', label: 'Prazo (dias)' },
			{ name: 'confidence', type: 'number', label: 'Confiança da velocidade' },
			{ name: 'speed_source', type: 'string', label: 'Fonte da velocidade' },
			{ name: 'estimate', type: 'number', label: 'Velocidade estimada' },
			{ name: 'minutes_unit', type: 'number', label: 'Minutos por peça' },
			{ name: 'warnings', type: 'string', label: 'Avisos' },
		],
	},

	/* ── CAD (cad.ts) ── */
	{
		id: 'cad.assembly',
		label: 'Montagem 3D',
		sub: 'Converte o desenho 2D na montagem 3D para prévia interativa',
		icon: 'Boxes',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'sketch',
				kind: 'ref',
				refType: 'string',
				label: 'Desenho (sketch)',
				hint: 'Saída sketch de um bloco gerador cad.* (caixa, troféu, medalha…) ou JSON colado',
				required: true,
				widget: 'textarea',
			},
		],
		outputs: [
			{ name: 'assembly', type: 'string', label: 'Montagem 3D (objeto)' },
			{ name: 'json', type: 'string', label: 'Montagem 3D (JSON)' },
			{ name: 'part_count', type: 'number', label: 'Nº de peças' },
		],
	},
	{
		id: 'cad.nest',
		label: 'Nesting de chapa',
		sub: 'Encaixa as peças do desenho em chapas com MaxRects',
		icon: 'LayoutGrid',
		accent: 'cyan',
		category: 'image',
		params: [
			{
				name: 'sketch',
				kind: 'ref',
				refType: 'string',
				label: 'Desenho (sketch)',
				hint: 'Saída sketch de um bloco gerador cad.* ou JSON colado',
				required: true,
				widget: 'textarea',
			},
			{
				name: 'chapa_w',
				kind: 'literal',
				valueType: 'number',
				label: 'Largura da chapa (mm)',
				hint: 'Largura útil da chapa de material',
				default: 600,
				min: 1,
				max: 20000,
				step: 1,
				required: true,
			},
			{
				name: 'chapa_h',
				kind: 'literal',
				valueType: 'number',
				label: 'Altura da chapa (mm)',
				hint: 'Altura útil da chapa de material',
				default: 400,
				min: 1,
				max: 20000,
				step: 1,
				required: true,
			},
			{
				name: 'margem',
				kind: 'literal',
				valueType: 'number',
				label: 'Margem da chapa (mm)',
				hint: 'Borda interna não usada para corte',
				default: 5,
				min: 0,
				max: 200,
				step: 0.1,
				required: true,
			},
			{
				name: 'rotacao',
				kind: 'literal',
				valueType: 'bool',
				label: 'Permitir rotação de peças',
				hint: 'Desligue para material com veio/direção (compensado, acrílico texturizado)',
				default: true,
				required: true,
			},
			{
				name: 'gap',
				kind: 'literal',
				valueType: 'number',
				label: 'Espaçamento entre peças (mm)',
				hint: 'Em branco usa max(2×kerf, 1,5 mm) do próprio desenho',
				min: 0,
				max: 200,
				step: 0.1,
			},
		],
		outputs: [
			{
				name: 'result',
				type: 'string',
				label: 'Resultado do nesting (objeto)',
			},
			{ name: 'sheets_used', type: 'number', label: 'Chapas usadas' },
			{
				name: 'utilization',
				type: 'number',
				label: 'Aproveitamento por chapa',
			},
			{
				name: 'unplaced',
				type: 'string',
				label: 'Peças que não couberam (ids)',
			},
			{
				name: 'unplaced_count',
				type: 'number',
				label: 'Qtd. de peças não alocadas',
			},
		],
	},
	{
		id: 'cad.render_svg',
		label: 'Renderizar SVG',
		sub: 'Desenha o sketch como SVG em escala real (mm)',
		icon: 'FileImage',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'sketch',
				kind: 'ref',
				refType: 'string',
				label: 'Desenho (sketch)',
				hint: 'Saída sketch de um bloco gerador cad.* ou JSON colado',
				required: true,
				widget: 'textarea',
			},
			{
				name: 'nest',
				kind: 'ref',
				refType: 'string',
				label: 'Nesting (resultado cad.nest)',
				hint: 'Obrigatório no modo chapa; ignorado no modo peças. Em branco no modo chapa renderiza sem positions',
				widget: 'textarea',
			},
			{
				name: 'modo',
				kind: 'literal',
				valueType: 'enum',
				label: 'Modo de renderização',
				hint: 'chapa = simulação da chapa com nesting; pecas = peças distintas lado a lado (conferição)',
				default: 'chapa',
				options: ['chapa', 'pecas'],
				required: true,
			},
			{
				name: 'folha',
				kind: 'literal',
				valueType: 'int',
				label: 'Folha a desenhar (índice 0-based)',
				hint: 'Qual chapa desenhar quando o nesting usou mais de uma',
				default: 0,
				min: 0,
				max: 200,
				step: 1,
				required: true,
			},
			{
				name: 'fundo',
				kind: 'literal',
				valueType: 'string',
				label: 'Cor de fundo do SVG',
				hint: 'Ex.: #ffffff. Vazio deixa transparente',
				default: '',
			},
		],
		outputs: [
			{ name: 'svg', type: 'string', label: 'SVG em escala real (mm)' },
			{ name: 'dataUrl', type: 'string', label: 'SVG como data URL (base64)' },
		],
	},

	/* ── Estúdio / dispatch (dispatch.ts) ── */
	{
		id: 'ai.studio',
		label: 'Estúdio de IA',
		sub: 'Remover fundo, colorir, restaurar ou ampliar',
		icon: 'Sparkles',
		accent: 'violet',
		category: 'ai',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				hint: 'Saída PNG de um nó anterior (ex.: upload ou filtro).',
				required: true,
			},
			{
				name: 'operation',
				kind: 'literal',
				valueType: 'enum',
				label: 'Operação',
				hint: 'remover_fundo = chroma-key (grátis); colorir/restaurar = Gemini; ampliar = Lanczos.',
				default: 'remover_fundo',
				options: ['remover_fundo', 'colorir', 'restaurar', 'ampliar'],
				required: true,
			},
			{
				name: 'factor',
				kind: 'literal',
				valueType: 'enum',
				label: 'Fator de ampliação',
				hint: 'Usado apenas em ampliar (image.upscale).',
				default: '2',
				options: ['2', '4', '8', '16'],
			},
		],
		outputs: [
			{ name: 'png', type: 'buffer', label: 'PNG' },
			{ name: 'pngBase64', type: 'string', label: 'PNG (base64)' },
		],
	},
	{
		id: 'image.effect',
		label: 'Efeito de imagem',
		sub: 'Sépia, duotone, desenho, óleo, quadrinhos…',
		icon: 'Wand2',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				hint: 'Saída PNG de um nó anterior.',
				required: true,
			},
			{
				name: 'effect',
				kind: 'literal',
				valueType: 'enum',
				label: 'Efeito',
				hint: 'nenhum = passa a imagem direto (identidade).',
				default: 'nenhum',
				options: [
					'sepia',
					'duotone',
					'desenho',
					'pontos',
					'pixel',
					'vinheta',
					'glitch',
					'oleo',
					'quadrinhos',
					'pontilhismo',
					'brilho_suave',
					'cross_process',
					'split_toning',
					'vazamento_luz',
					'nenhum',
				],
				required: true,
			},
			{
				name: 'intensity',
				kind: 'literal',
				valueType: 'number',
				label: 'Intensidade',
				hint: '0 = sem efeito, 1 = efeito cheio (blocos que suportam).',
				default: 1,
				min: 0,
				max: 1,
				step: 0.05,
			},
		],
		outputs: [
			{ name: 'png', type: 'buffer', label: 'PNG' },
			{ name: 'pngBase64', type: 'string', label: 'PNG (base64)' },
		],
	},
	{
		id: 'cad.generate',
		label: 'Gerador CAD',
		sub: 'Caixa, churrasqueira, troféu ou medalha paramétricos',
		icon: 'Shapes',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'modelo',
				kind: 'literal',
				valueType: 'enum',
				label: 'Modelo',
				hint: 'Escolhe o gerador cad.*. Os parâmetros próprios de cada modelo passam direto (schema passthrough).',
				default: 'caixa',
				options: ['churrasqueira', 'caixa', 'trofeu', 'medalha'],
				required: true,
			},
		],
		outputs: [
			{ name: 'sketch', type: 'string', label: 'Desenho (sketch IR)' },
			{ name: 'warnings', type: 'string', label: 'Avisos do gerador' },
			{ name: 'part_count', type: 'number', label: 'Nº de peças' },
			{
				name: 'cut_length_mm',
				type: 'number',
				label: 'Comprimento de corte (mm)',
			},
			{
				name: 'engrave_length_mm',
				type: 'number',
				label: 'Comprimento de gravação (mm)',
			},
			{ name: 'pierces', type: 'number', label: 'Nº de furos' },
		],
	},

	/* ── Exportação (output-cad.ts / output-extra.ts) ── */
	{
		id: 'output.export_dxf_v2',
		label: 'Exportar DXF (CAD)',
		sub: 'Desenho CAD → DXF em mm com camadas por operação',
		icon: 'FileDown',
		accent: 'orange',
		category: 'output',
		params: [
			{
				name: 'sketch',
				kind: 'ref',
				refType: 'string',
				label: 'Desenho (sketch)',
				hint: 'Saída de um bloco cad.* (Sketch2D serializado)',
				required: true,
			},
			{
				name: 'nest',
				kind: 'ref',
				refType: 'string',
				label: 'Nesting (opcional)',
				hint: 'Resultado de um bloco cad.nest (NestResult serializado)',
				required: false,
			},
			{
				name: 'folder',
				kind: 'literal',
				valueType: 'string',
				label: 'Pasta no storage',
				default: 'tool-output',
			},
		],
		outputs: [{ name: 'url', type: 'string', label: 'URL do DXF' }],
	},
	{
		id: 'output.export_svg_sheet',
		label: 'Exportar SVG da chapa',
		sub: 'Chapa do desenho CAD → SVG em escala real (mm)',
		icon: 'Files',
		accent: 'amber',
		category: 'output',
		params: [
			{
				name: 'sketch',
				kind: 'ref',
				refType: 'string',
				label: 'Desenho (sketch)',
				hint: 'Saída de um bloco cad.* (Sketch2D serializado)',
				required: true,
			},
			{
				name: 'nest',
				kind: 'ref',
				refType: 'string',
				label: 'Nesting (opcional)',
				hint: 'Resultado de um bloco cad.nest (NestResult serializado)',
				required: false,
			},
			{
				name: 'folha',
				kind: 'literal',
				valueType: 'int',
				label: 'Índice da chapa',
				hint: 'Qual chapa exportar (0-based)',
				default: 0,
				min: 0,
				max: 200,
				step: 1,
			},
			{
				name: 'folder',
				kind: 'literal',
				valueType: 'string',
				label: 'Pasta no storage',
				default: 'tool-output',
			},
		],
		outputs: [{ name: 'url', type: 'string', label: 'URL do SVG' }],
	},
	{
		id: 'output.export_lbrn2',
		label: 'Exportar LightBurn (.lbrn2)',
		sub: 'PNG → .lbrn2 mínimo dimensionado em mm',
		icon: 'FileBox',
		accent: 'orange',
		category: 'output',
		params: [
			{
				name: 'from',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem PNG',
				hint: 'Buffer PNG de um bloco de imagem',
				required: true,
			},
			{
				name: 'width_mm',
				kind: 'literal',
				valueType: 'number',
				label: 'Largura física (mm)',
				hint: 'Altura calculada pela proporção real da imagem',
				default: 100,
				min: 0.001,
				max: 2000,
				step: 0.1,
			},
			{
				name: 'folder',
				kind: 'literal',
				valueType: 'string',
				label: 'Pasta no storage',
				default: 'tool-output',
			},
		],
		outputs: [{ name: 'url', type: 'string', label: 'URL do .lbrn2' }],
	},

	/* ── Export DXF v1 (output-extra.ts) ── */
	{
		id: 'output.export_dxf',
		label: 'Exportar DXF',
		sub: 'Converte SVG em arquivo de corte .dxf',
		icon: 'FileDown',
		accent: 'orange',
		category: 'output',
		params: [
			{
				name: 'from',
				kind: 'ref',
				refType: 'string',
				label: 'SVG de origem',
				hint: 'SVG (string) de outro nó a ser convertido em DXF de corte',
				required: true,
			},
			{
				name: 'folder',
				kind: 'literal',
				valueType: 'string',
				label: 'Pasta de destino',
				hint: 'Pasta no storage onde o .dxf será salvo',
				default: 'tool-output',
			},
		],
		outputs: [{ name: 'url', type: 'string', label: 'URL pública do DXF' }],
	},

	/* ── IA de texto (ai-text.ts) ── */
	{
		id: 'ai.text',
		label: 'IA de Texto',
		sub: 'Raciocínio/redação por LLM com sistema + prompt',
		icon: 'Sparkles',
		accent: 'violet',
		category: 'ai',
		params: [
			{
				name: 'system',
				kind: 'ref',
				refType: 'string',
				label: 'Prompt de sistema',
				hint: 'Papel/regras injetadas pelo motor (definition.text_system_prompt)',
				default: '',
			},
			{
				name: 'user',
				kind: 'ref',
				refType: 'string',
				label: 'Prompt do usuário',
				hint: 'Instrução enviada ao LLM (normalmente vem de util.text_template)',
				required: true,
				widget: 'textarea',
			},
			{
				name: 'model',
				kind: 'literal',
				valueType: 'string',
				label: 'Modelo de texto',
				hint: 'Override injetado do definition.text_model; validado contra o catálogo curado',
				default: '',
			},
			{
				name: 'json',
				kind: 'literal',
				valueType: 'bool',
				label: 'Saída estruturada (JSON)',
				hint: 'Pede saída estruturada — devolve também o campo json',
				default: false,
			},
			{
				name: 'temperature',
				kind: 'literal',
				valueType: 'number',
				label: 'Temperatura',
				default: 0.3,
				min: 0,
				max: 2,
				step: 0.1,
			},
			{
				name: 'max_tokens',
				kind: 'literal',
				valueType: 'int',
				label: 'Máx. de tokens',
				default: 1200,
				min: 1,
				max: 16000,
				step: 1,
			},
		],
		outputs: [
			{ name: 'text', type: 'string', label: 'Texto gerado' },
			{
				name: 'json',
				type: 'string',
				label: 'JSON extraído (quando json=true)',
			},
			{ name: 'model', type: 'string', label: 'Modelo usado' },
		],
	},

	/* ── Dithering dispatcher (dispatch.ts) ── */
	{
		id: 'image.dither',
		label: 'Dithering P&B',
		sub: 'Binariza P&B com o algoritmo escolhido — dispatcher dos blocos dither.*',
		icon: 'Dot',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				hint: 'Imagem raster de entrada (PNG/JPEG).',
				required: true,
			},
			{
				name: 'algorithm',
				kind: 'literal',
				valueType: 'enum',
				label: 'Algoritmo',
				hint: 'Algoritmo de dithering/binarização.',
				default: 'floydSteinberg',
				options: [
					'floydSteinberg',
					'atkinson',
					'jarvis',
					'stucki',
					'sierra',
					'sierra2',
					'sierraLite',
					'burkes',
					'bayer8',
					'bayer4',
					'halftone',
					'blueNoise',
					'errorDiffusion',
				],
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Limiar',
				hint: 'Limiar de binarização (0–255). Algoritmos ordered/halftone ignoram.',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
				required: true,
			},
		],
		outputs: [
			{ name: 'png', type: 'buffer', label: 'PNG binarizado' },
			{ name: 'pngBase64', type: 'string', label: 'PNG (base64 data URL)' },
		],
	},

	/* ── Coleções da Fábrica (collection.ts) ── */
	{
		id: 'collection.nearest',
		label: 'Registro Mais Próximo',
		sub: 'Interpola o registro mais próximo de uma coleção (ex.: receita para espessura inexistente)',
		icon: 'Radar',
		accent: 'sky',
		category: 'util',
		params: [
			{
				name: 'tool',
				kind: 'ref',
				refType: 'string',
				label: 'Tool dona da coleção',
				required: true,
			},
			{
				name: 'collection',
				kind: 'literal',
				valueType: 'string',
				label: 'Coleção',
				default: 'default',
				required: true,
			},
			{
				name: 'target',
				kind: 'literal',
				valueType: 'string',
				label: 'Alvo (JSON)',
				hint: 'Ex.: {"espessura_mm":3,"potencia_w":1500} — alvo da interpolação',
				widget: 'textarea',
				required: true,
			},
			{
				name: 'group',
				kind: 'literal',
				valueType: 'string',
				label: 'Grupo restrito (JSON)',
				hint: 'Ex.: {"material":"aco_carbono"} — restringe ao grupo comparável',
				widget: 'textarea',
			},
			{
				name: 'limit',
				kind: 'literal',
				valueType: 'int',
				label: 'Limite de resultados',
				default: 3,
				min: 1,
				max: 25,
				step: 1,
			},
		],
		outputs: [
			{ name: 'json', type: 'string', label: 'Itens (JSON)' },
			{ name: 'first', type: 'string', label: 'Registro mais próximo (JSON)' },
			{ name: 'found', type: 'number', label: 'Encontrou (1/0)' },
			{ name: 'exact', type: 'number', label: 'Resultado exato (1/0)' },
		],
	},
	{
		id: 'collection.query',
		label: 'Consultar Coleção',
		sub: 'Busca registros aprovados de uma coleção com filtros, faixas e texto livre',
		icon: 'Database',
		accent: 'cyan',
		category: 'util',
		params: [
			{
				name: 'tool',
				kind: 'ref',
				refType: 'string',
				label: 'Tool dona da coleção',
				hint: 'Ex.: metallic — pode ser outra tool, é assim que o orçamento lê a base do Metallic',
				required: true,
			},
			{
				name: 'collection',
				kind: 'literal',
				valueType: 'string',
				label: 'Coleção',
				hint: 'Identificador da coleção dentro da tool',
				default: 'default',
				required: true,
			},
			{
				name: 'filters',
				kind: 'literal',
				valueType: 'string',
				label: 'Filtros (JSON)',
				hint: 'Ex.: {"material":"aco_carbono","operacao":"corte"} — correspondência exata',
				widget: 'textarea',
			},
			{
				name: 'ranges',
				kind: 'literal',
				valueType: 'string',
				label: 'Faixas numéricas (JSON)',
				hint: 'Ex.: {"espessura_mm":{"min":2,"max":4}}',
				widget: 'textarea',
			},
			{
				name: 'q',
				kind: 'literal',
				valueType: 'string',
				label: 'Busca textual',
				hint: 'Texto livre para busca por relevância',
				max: 200,
			},
			{
				name: 'sort',
				kind: 'literal',
				valueType: 'string',
				label: 'Ordenação',
				default: 'score',
				max: 20,
			},
			{
				name: 'limit',
				kind: 'literal',
				valueType: 'int',
				label: 'Limite de resultados',
				default: 5,
				min: 1,
				max: 50,
				step: 1,
			},
		],
		outputs: [
			{ name: 'json', type: 'string', label: 'Itens (JSON)' },
			{ name: 'count', type: 'number', label: 'Total de registros' },
			{ name: 'first', type: 'string', label: 'Melhor item (JSON)' },
			{ name: 'found', type: 'number', label: 'Encontrou (1/0)' },
		],
	},

	/* ── Geradores CAD paramétricos (cad.ts) — normalmente acessíveis via
	   cad.generate, mas o autor pode usar direto. Specs por garantia. ── */
	{
		id: 'cad.box',
		label: 'Caixa paramétrica',
		sub: 'Encaixe de dente, tampa, divisórias',
		icon: 'Box',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'dim_mode',
				kind: 'literal',
				valueType: 'enum',
				label: 'Modo de medição',
				hint: 'interno = vão útil; externo = caixa montada',
				default: 'interno',
				options: ['interno', 'externo'],
			},
			{
				name: 'largura',
				kind: 'literal',
				valueType: 'number',
				label: 'Largura (mm)',
				min: 1,
				max: 3000,
				step: 1,
				required: true,
			},
			{
				name: 'profundidade',
				kind: 'literal',
				valueType: 'number',
				label: 'Profundidade (mm)',
				min: 1,
				max: 3000,
				step: 1,
				required: true,
			},
			{
				name: 'altura',
				kind: 'literal',
				valueType: 'number',
				label: 'Altura (mm)',
				min: 1,
				max: 3000,
				step: 1,
				required: true,
			},
			{
				name: 'espessura',
				kind: 'literal',
				valueType: 'number',
				label: 'Espessura do material (mm)',
				min: 0.1,
				max: 50,
				step: 0.1,
				required: true,
			},
			{
				name: 'material',
				kind: 'literal',
				valueType: 'string',
				label: 'Material',
				default: 'MDF',
			},
			{
				name: 'kerf',
				kind: 'literal',
				valueType: 'number',
				label: 'Kerf (mm)',
				hint: 'Largura do risco do feixe',
				default: 0.15,
				min: 0,
				max: 3,
				step: 0.05,
			},
			{
				name: 'folga',
				kind: 'literal',
				valueType: 'number',
				label: 'Folga de encaixe (mm)',
				default: 0.1,
				min: 0.05,
				max: 1,
				step: 0.05,
			},
			{
				name: 'encaixe',
				kind: 'literal',
				valueType: 'enum',
				label: 'Tipo de encaixe',
				default: 'dente',
				options: ['dente', 'dente_reforcado', 'topo_colado'],
			},
			{
				name: 'dente_alvo',
				kind: 'literal',
				valueType: 'number',
				label: 'Largura do dente (mm)',
				hint: 'Vazio usa max(3t, 8) em [6, 25]',
				min: 1,
				max: 100,
				step: 0.5,
			},
			{
				name: 'fundo',
				kind: 'literal',
				valueType: 'bool',
				label: 'Com fundo',
				default: true,
			},
			{
				name: 'tampa',
				kind: 'literal',
				valueType: 'enum',
				label: 'Tampa',
				default: 'nenhuma',
				options: ['nenhuma', 'deslizante', 'encaixe', 'solta'],
			},
			{
				name: 'tampa_folga',
				kind: 'literal',
				valueType: 'number',
				label: 'Folga da tampa (mm)',
				default: 0.2,
				min: 0,
				max: 3,
				step: 0.05,
			},
			{
				name: 'div_x',
				kind: 'literal',
				valueType: 'int',
				label: 'Divisórias em X',
				default: 0,
				min: 0,
				max: 20,
				step: 1,
			},
			{
				name: 'div_y',
				kind: 'literal',
				valueType: 'int',
				label: 'Divisórias em Y',
				default: 0,
				min: 0,
				max: 20,
				step: 1,
			},
			{
				name: 'div_altura_pct',
				kind: 'literal',
				valueType: 'number',
				label: 'Altura das divisórias (%)',
				default: 100,
				min: 1,
				max: 100,
				step: 1,
			},
			{
				name: 'gravacao_tampa',
				kind: 'literal',
				valueType: 'string',
				label: 'Gravação da tampa',
				default: '',
				widget: 'textarea',
			},
		],
		outputs: [
			{ name: 'sketch', type: 'string', label: 'Desenho (sketch IR)' },
			{ name: 'warnings', type: 'string', label: 'Avisos' },
			{ name: 'part_count', type: 'number', label: 'Nº de peças' },
			{
				name: 'cut_length_mm',
				type: 'number',
				label: 'Comprimento de corte (mm)',
			},
			{
				name: 'engrave_length_mm',
				type: 'number',
				label: 'Comprimento de gravação (mm)',
			},
			{ name: 'pierces', type: 'number', label: 'Furos/pierces' },
		],
	},
	{
		id: 'cad.bbq',
		label: 'Churrasqueira de chapa',
		sub: 'Dobrada, encaixada ou soldada, com pés e grelha',
		icon: 'Flame',
		accent: 'cyan',
		category: 'image',
		params: [
			{
				name: 'pessoas',
				kind: 'literal',
				valueType: 'int',
				label: 'Nº de pessoas',
				hint: 'Sobrescreve medidas (0,03 m²/pessoa, razão 2:1)',
				min: 0,
				max: 500,
				step: 1,
			},
			{
				name: 'comprimento',
				kind: 'literal',
				valueType: 'number',
				label: 'Comprimento (mm)',
				min: 1,
				max: 5000,
				step: 1,
			},
			{
				name: 'largura',
				kind: 'literal',
				valueType: 'number',
				label: 'Largura (mm)',
				min: 1,
				max: 3000,
				step: 1,
			},
			{
				name: 'profundidade',
				kind: 'literal',
				valueType: 'number',
				label: 'Profundidade da cuba (mm)',
				min: 1,
				max: 1000,
				step: 1,
			},
			{
				name: 'espessura',
				kind: 'literal',
				valueType: 'number',
				label: 'Espessura da chapa (mm)',
				min: 0.1,
				max: 50,
				step: 0.1,
				required: true,
			},
			{
				name: 'material',
				kind: 'literal',
				valueType: 'enum',
				label: 'Material',
				default: 'aco_carbono',
				options: ['aco_carbono', 'inox_304', 'inox_430', 'corten'],
			},
			{
				name: 'kerf',
				kind: 'literal',
				valueType: 'number',
				label: 'Kerf (mm)',
				hint: 'Fibra em aço risca mais largo',
				default: 0.2,
				min: 0,
				max: 3,
				step: 0.05,
			},
			{
				name: 'folga',
				kind: 'literal',
				valueType: 'number',
				label: 'Folga (mm)',
				default: 0.15,
				min: 0.05,
				max: 1,
				step: 0.05,
			},
			{
				name: 'construcao',
				kind: 'literal',
				valueType: 'enum',
				label: 'Construção',
				default: 'dobrada',
				options: ['dobrada', 'encaixada', 'soldada'],
			},
			{
				name: 'raio_dobra',
				kind: 'literal',
				valueType: 'number',
				label: 'Raio interno de dobra (mm)',
				hint: 'Vazio usa a espessura',
				min: 0,
				max: 100,
				step: 0.5,
			},
			{
				name: 'fator_k',
				kind: 'literal',
				valueType: 'number',
				label: 'Fator K',
				hint: 'Fibra neutra; vazio usa tabela do material',
				min: 0.01,
				max: 0.5,
				step: 0.01,
			},
			{
				name: 'pes',
				kind: 'literal',
				valueType: 'enum',
				label: 'Pés',
				default: 'nenhum',
				options: ['nenhum', 'chapa_dobrada', 'cruzado_x', 'abas'],
			},
			{
				name: 'altura_pes',
				kind: 'literal',
				valueType: 'number',
				label: 'Altura dos pés (mm)',
				min: 1,
				max: 2000,
				step: 1,
			},
			{
				name: 'grelha',
				kind: 'literal',
				valueType: 'enum',
				label: 'Grelha',
				default: 'nenhuma',
				options: ['nenhuma', 'chapa_vazada', 'varoes_apoio'],
			},
			{
				name: 'grelha_niveis',
				kind: 'literal',
				valueType: 'int',
				label: 'Níveis da grelha',
				min: 1,
				max: 6,
				step: 1,
			},
			{
				name: 'grelha_passo',
				kind: 'literal',
				valueType: 'number',
				label: 'Passo da grelha (mm)',
				min: 1,
				max: 100,
				step: 1,
			},
			{
				name: 'grelha_rasgo',
				kind: 'literal',
				valueType: 'number',
				label: 'Largura do rasgo da grelha (mm)',
				min: 1,
				max: 100,
				step: 1,
			},
			{
				name: 'respiros',
				kind: 'literal',
				valueType: 'enum',
				label: 'Respiros',
				default: 'nenhum',
				options: ['nenhum', 'furos', 'rasgos', 'fundo_perfurado'],
			},
			{
				name: 'respiro_area_pct',
				kind: 'literal',
				valueType: 'number',
				label: 'Área aberta dos respiros (%)',
				min: 0,
				max: 50,
				step: 1,
			},
			{
				name: 'cinzeiro',
				kind: 'literal',
				valueType: 'enum',
				label: 'Cinzeiro',
				default: 'nenhum',
				options: ['nenhum', 'gaveta', 'fundo_perfurado'],
			},
			{
				name: 'gravacao_frente',
				kind: 'literal',
				valueType: 'string',
				label: 'Gravação da frente',
				default: '',
				widget: 'textarea',
			},
		],
		outputs: [
			{ name: 'sketch', type: 'string', label: 'Desenho (sketch IR)' },
			{ name: 'warnings', type: 'string', label: 'Avisos' },
			{ name: 'part_count', type: 'number', label: 'Nº de peças' },
			{
				name: 'cut_length_mm',
				type: 'number',
				label: 'Comprimento de corte (mm)',
			},
			{
				name: 'engrave_length_mm',
				type: 'number',
				label: 'Comprimento de gravação (mm)',
			},
			{ name: 'pierces', type: 'number', label: 'Furos/pierces' },
		],
	},
	{
		id: 'cad.medal',
		label: 'Medalha plana',
		sub: 'Disco, estrela, polígono ou escudo com furo e aro',
		icon: 'Medal',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'diametro',
				kind: 'literal',
				valueType: 'number',
				label: 'Diâmetro (mm)',
				min: 1,
				max: 2000,
				step: 1,
				required: true,
			},
			{
				name: 'espessura',
				kind: 'literal',
				valueType: 'number',
				label: 'Espessura (mm)',
				min: 0.1,
				max: 50,
				step: 0.1,
				required: true,
			},
			{
				name: 'material',
				kind: 'literal',
				valueType: 'enum',
				label: 'Material',
				default: 'mdf',
				options: ['mdf', 'acrilico', 'compensado'],
			},
			{
				name: 'kerf',
				kind: 'literal',
				valueType: 'number',
				label: 'Kerf (mm)',
				default: 0.15,
				min: 0,
				max: 3,
				step: 0.05,
			},
			{
				name: 'forma',
				kind: 'literal',
				valueType: 'enum',
				label: 'Forma',
				default: 'disco',
				options: ['disco', 'estrela', 'poligono', 'escudo'],
			},
			{
				name: 'lados',
				kind: 'literal',
				valueType: 'int',
				label: 'Nº de lados/pontas',
				hint: 'Vale só para polígono e estrela',
				min: 3,
				max: 12,
				step: 1,
			},
			{
				name: 'furo_fita_diametro',
				kind: 'literal',
				valueType: 'number',
				label: 'Diâmetro do furo da fita (mm)',
				hint: '0 = sem furo',
				min: 0,
				max: 100,
				step: 0.5,
			},
			{
				name: 'furo_distancia_borda',
				kind: 'literal',
				valueType: 'number',
				label: 'Distância do furo à borda (mm)',
				min: 0,
				max: 1000,
				step: 1,
			},
			{
				name: 'aro',
				kind: 'literal',
				valueType: 'enum',
				label: 'Aro',
				default: 'nenhum',
				options: ['nenhum', 'simples', 'duplo'],
			},
			{
				name: 'gravacao_texto',
				kind: 'literal',
				valueType: 'string',
				label: 'Texto de gravação 1',
				default: '',
				widget: 'textarea',
			},
			{
				name: 'gravacao_texto2',
				kind: 'literal',
				valueType: 'string',
				label: 'Texto de gravação 2',
				default: '',
				widget: 'textarea',
			},
			{
				name: 'gravacao_altura',
				kind: 'literal',
				valueType: 'number',
				label: 'Altura da gravação (mm)',
				min: 0.5,
				max: 200,
				step: 0.5,
			},
			{
				name: 'qtd',
				kind: 'literal',
				valueType: 'int',
				label: 'Quantidade a cortar',
				hint: 'Multiplica o nesting',
				min: 1,
				max: 500,
				step: 1,
			},
		],
		outputs: [
			{ name: 'sketch', type: 'string', label: 'Desenho (sketch IR)' },
			{ name: 'warnings', type: 'string', label: 'Avisos' },
			{ name: 'part_count', type: 'number', label: 'Nº de peças' },
			{
				name: 'cut_length_mm',
				type: 'number',
				label: 'Comprimento de corte (mm)',
			},
			{
				name: 'engrave_length_mm',
				type: 'number',
				label: 'Comprimento de gravação (mm)',
			},
			{ name: 'pierces', type: 'number', label: 'Furos/pierces' },
		],
	},
	{
		id: 'cad.trophy',
		label: 'Troféu de encaixe',
		sub: 'Base + hastes em cross lap + placa, sem cola',
		icon: 'Trophy',
		accent: 'cyan',
		category: 'image',
		params: [
			{
				name: 'altura_total',
				kind: 'literal',
				valueType: 'number',
				label: 'Altura total (mm)',
				min: 1,
				max: 3000,
				step: 1,
				required: true,
			},
			{
				name: 'espessura',
				kind: 'literal',
				valueType: 'number',
				label: 'Espessura (mm)',
				min: 0.1,
				max: 50,
				step: 0.1,
				required: true,
			},
			{
				name: 'material',
				kind: 'literal',
				valueType: 'enum',
				label: 'Material',
				default: 'mdf',
				options: ['mdf', 'acrilico', 'compensado'],
			},
			{
				name: 'kerf',
				kind: 'literal',
				valueType: 'number',
				label: 'Kerf (mm)',
				default: 0.15,
				min: 0,
				max: 3,
				step: 0.05,
			},
			{
				name: 'folga',
				kind: 'literal',
				valueType: 'number',
				label: 'Folga (mm)',
				default: 0.1,
				min: 0.05,
				max: 1,
				step: 0.05,
			},
			{
				name: 'base_largura',
				kind: 'literal',
				valueType: 'number',
				label: 'Largura da base (mm)',
				hint: 'Vazio usa 0,5 × altura',
				min: 1,
				max: 3000,
				step: 1,
			},
			{
				name: 'base_profundidade',
				kind: 'literal',
				valueType: 'number',
				label: 'Profundidade da base (mm)',
				min: 1,
				max: 3000,
				step: 1,
			},
			{
				name: 'base_espessura',
				kind: 'literal',
				valueType: 'number',
				label: 'Espessura da base (mm)',
				hint: 'Vazio usa max(2t, 6)',
				min: 1,
				max: 100,
				step: 0.5,
			},
			{
				name: 'silhueta',
				kind: 'literal',
				valueType: 'enum',
				label: 'Silhueta da haste',
				default: 'conica',
				options: ['conica', 'reta', 'taca', 'estrela'],
			},
			{
				name: 'placa',
				kind: 'literal',
				valueType: 'enum',
				label: 'Placa',
				default: 'retangular',
				options: ['nenhuma', 'retangular', 'escudo'],
			},
			{
				name: 'placa_altura',
				kind: 'literal',
				valueType: 'number',
				label: 'Altura da placa (mm)',
				hint: 'Vazio usa 0,16 × altura',
				min: 1,
				max: 1000,
				step: 1,
			},
			{
				name: 'gravacao_placa',
				kind: 'literal',
				valueType: 'string',
				label: 'Texto da placa',
				default: '',
				widget: 'textarea',
			},
			{
				name: 'gravacao_altura',
				kind: 'literal',
				valueType: 'number',
				label: 'Altura da gravação (mm)',
				hint: 'Vazio usa max(4, 0,35 × placa_altura)',
				min: 0.5,
				max: 200,
				step: 0.5,
			},
			{
				name: 'fixacao',
				kind: 'literal',
				valueType: 'enum',
				label: 'Fixação',
				default: 'encaixe',
				options: ['encaixe', 'parafuso'],
			},
		],
		outputs: [
			{ name: 'sketch', type: 'string', label: 'Desenho (sketch IR)' },
			{ name: 'warnings', type: 'string', label: 'Avisos' },
			{ name: 'part_count', type: 'number', label: 'Nº de peças' },
			{
				name: 'cut_length_mm',
				type: 'number',
				label: 'Comprimento de corte (mm)',
			},
			{
				name: 'engrave_length_mm',
				type: 'number',
				label: 'Comprimento de gravação (mm)',
			},
			{ name: 'pierces', type: 'number', label: 'Furos/pierces' },
		],
	},
];
