/**
 * Catálogo ImagR (GERADO por scripts/export-imagr-manifest.ts + gerador do front).
 * 97 blocos espelhando o registry do main API, pra o builder/canvas
 * combinar/editar os filtros. NÃO editar à mão — regenerar do manifesto.
 */
import type { BlockSpec } from './block-catalog';

export const IMAGR_BLOCKS: BlockSpec[] = [
	{
		id: 'adjust.adaptiveThreshold',
		label: 'Limiar Adaptativo',
		sub: 'Limiar adaptativo: compara cada pixel com a média local (rai',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'radius',
				kind: 'literal',
				valueType: 'number',
				label: 'Radius',
				default: 6,
				min: 1,
				max: 40,
				step: 1,
			},
			{
				name: 'bias',
				kind: 'literal',
				valueType: 'number',
				label: 'Bias',
				default: 0,
				min: -0.5,
				max: 0.5,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.autoContrast',
		label: 'Contraste Automático',
		sub: 'Contraste automático (normaliza pro range completo).',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.autoLevels',
		label: 'Níveis Automáticos',
		sub: 'Níveis automáticos: estica o histograma (com clip de percent',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'clip',
				kind: 'literal',
				valueType: 'number',
				label: 'Clip',
				default: 0.5,
				min: 0,
				max: 10,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.autoRefine',
		label: 'Refino Automático',
		sub: 'Refino local de contraste (CLAHE) por blocos.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'clipLimit',
				kind: 'literal',
				valueType: 'number',
				label: 'Clip Limit',
				default: 2,
				min: 0,
				max: 10,
				step: 1,
			},
			{
				name: 'tileX',
				kind: 'literal',
				valueType: 'number',
				label: 'Tile X',
				default: 8,
				min: 3,
				max: 512,
				step: 1,
			},
			{
				name: 'tileY',
				kind: 'literal',
				valueType: 'number',
				label: 'Tile Y',
				default: 8,
				min: 3,
				max: 512,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.brightness',
		label: 'Brilho',
		sub: 'Brilho (-1 a 1): clareia/escurece somando luz.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'value',
				kind: 'literal',
				valueType: 'number',
				label: 'Value',
				default: 0,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.bwLevels',
		label: 'Níveis P&B',
		sub: 'Níveis P&B: grayscale + estica [input_min,input_max] pra 0..',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'input_min',
				kind: 'literal',
				valueType: 'number',
				label: 'Input Min',
				default: 0,
				step: 0.01,
			},
			{
				name: 'input_max',
				kind: 'literal',
				valueType: 'number',
				label: 'Input Max',
				default: 255,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.channelMixer',
		label: 'Mixer de Canais',
		sub: 'Mixer de canais: recombina R,G,B (matriz 3×3).',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'rr',
				kind: 'literal',
				valueType: 'number',
				label: 'Rr',
				default: 1,
				step: 0.01,
			},
			{
				name: 'rg',
				kind: 'literal',
				valueType: 'number',
				label: 'Rg',
				default: 0,
				step: 0.01,
			},
			{
				name: 'rb',
				kind: 'literal',
				valueType: 'number',
				label: 'Rb',
				default: 0,
				step: 0.01,
			},
			{
				name: 'gr',
				kind: 'literal',
				valueType: 'number',
				label: 'Gr',
				default: 0,
				step: 0.01,
			},
			{
				name: 'gg',
				kind: 'literal',
				valueType: 'number',
				label: 'Gg',
				default: 1,
				step: 0.01,
			},
			{
				name: 'gb',
				kind: 'literal',
				valueType: 'number',
				label: 'Gb',
				default: 0,
				step: 0.01,
			},
			{
				name: 'br',
				kind: 'literal',
				valueType: 'number',
				label: 'Br',
				default: 0,
				step: 0.01,
			},
			{
				name: 'bg',
				kind: 'literal',
				valueType: 'number',
				label: 'Bg',
				default: 0,
				step: 0.01,
			},
			{
				name: 'bb',
				kind: 'literal',
				valueType: 'number',
				label: 'Bb',
				default: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.contrast',
		label: 'Contraste',
		sub: 'Contraste (-1 a 1) em torno do tom médio.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'value',
				kind: 'literal',
				valueType: 'number',
				label: 'Value',
				default: 0,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.curves',
		label: 'Curvas',
		sub: 'Curva por 3 pontos: preto (low), meio (mid) e branco (high).',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'low',
				kind: 'literal',
				valueType: 'number',
				label: 'Low',
				default: 0,
				min: 0,
				max: 255,
				step: 1,
			},
			{
				name: 'mid',
				kind: 'literal',
				valueType: 'number',
				label: 'Mid',
				default: 128,
				min: 1,
				max: 254,
				step: 1,
			},
			{
				name: 'high',
				kind: 'literal',
				valueType: 'number',
				label: 'High',
				default: 255,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.dehaze',
		label: 'Remover Névoa',
		sub: 'Remove névoa (aprox.): reforça contraste e saturação.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'amount',
				kind: 'literal',
				valueType: 'number',
				label: 'Amount',
				default: 0.6,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'strength',
				kind: 'literal',
				valueType: 'number',
				label: 'Strength',
				default: 1,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.exposure',
		label: 'Exposição',
		sub: 'Exposição em stops (-4 a 4): multiplica a luz por 2^stops.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'stops',
				kind: 'literal',
				valueType: 'number',
				label: 'Stops',
				default: 0,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.gamma',
		label: 'Gama',
		sub: 'Gama (0.1 a 3): curva tonal out=(in/255)^(1/gamma).',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'value',
				kind: 'literal',
				valueType: 'number',
				label: 'Value',
				default: 1,
				min: 0.1,
				max: 3,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.gradientMap',
		label: 'Mapa de Gradiente',
		sub: 'Mapa de gradiente: mapeia o tom entre duas cores.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'shadowColor',
				kind: 'literal',
				valueType: 'string',
				label: 'Shadow Color',
				default: '#000000',
			},
			{
				name: 'highlightColor',
				kind: 'literal',
				valueType: 'string',
				label: 'Highlight Color',
				default: '#ffffff',
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.grayscale',
		label: 'Escala de Cinza',
		sub: 'Escala de cinza (Rec.709).',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.highlightsShadows',
		label: 'Luzes e Sombras',
		sub: 'Sombras/altas-luzes: levanta sombras e/ou recupera luzes.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'shadows',
				kind: 'literal',
				valueType: 'number',
				label: 'Shadows',
				default: 0,
				min: -1,
				max: 1,
				step: 0.01,
			},
			{
				name: 'highlights',
				kind: 'literal',
				valueType: 'number',
				label: 'Highlights',
				default: 0,
				min: -1,
				max: 1,
				step: 0.01,
			},
			{
				name: 'strength',
				kind: 'literal',
				valueType: 'number',
				label: 'Strength',
				default: 1,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.histogramStretch',
		label: 'Equalizar Histograma',
		sub: 'Estica o histograma pro range completo.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.hsl',
		label: 'Matiz, Saturação e Luz',
		sub: 'HSL: matiz (giro), saturação (mult) e luminosidade (soma).',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'hue',
				kind: 'literal',
				valueType: 'number',
				label: 'Hue',
				default: 0,
				min: -0.5,
				max: 0.5,
				step: 0.01,
			},
			{
				name: 'sat',
				kind: 'literal',
				valueType: 'number',
				label: 'Sat',
				default: 1,
				min: 0,
				max: 3,
				step: 0.01,
			},
			{
				name: 'light',
				kind: 'literal',
				valueType: 'number',
				label: 'Light',
				default: 0,
				min: -0.5,
				max: 0.5,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.hue',
		label: 'Matiz',
		sub: 'Matiz (-180 a 180 graus): gira a roda de cores.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'degrees',
				kind: 'literal',
				valueType: 'number',
				label: 'Degrees',
				default: 0,
				min: -180,
				max: 180,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.levels',
		label: 'Níveis',
		sub: 'Níveis: remapeia [inputMin,inputMax] → [outputMin,outputMax]',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'inputMin',
				kind: 'literal',
				valueType: 'number',
				label: 'Input Min',
				default: 0,
				step: 0.01,
			},
			{
				name: 'inputMax',
				kind: 'literal',
				valueType: 'number',
				label: 'Input Max',
				default: 255,
				step: 0.01,
			},
			{
				name: 'outputMin',
				kind: 'literal',
				valueType: 'number',
				label: 'Output Min',
				default: 0,
				step: 0.01,
			},
			{
				name: 'outputMax',
				kind: 'literal',
				valueType: 'number',
				label: 'Output Max',
				default: 255,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.monochrome',
		label: 'Monocromático',
		sub: 'Monocromático: grayscale com leve contraste de filme.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'filmContrast',
				kind: 'literal',
				valueType: 'number',
				label: 'Film Contrast',
				default: 0.12,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.posterize',
		label: 'Posterizar',
		sub: 'Posterização: reduz pra N níveis por canal.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'levels',
				kind: 'literal',
				valueType: 'int',
				label: 'Levels',
				default: 6,
				min: 2,
				max: 32,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.saturation',
		label: 'Saturação',
		sub: 'Saturação (-1 a 1).',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'value',
				kind: 'literal',
				valueType: 'number',
				label: 'Value',
				default: 0,
				min: -1,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.temperature',
		label: 'Temperatura de Cor',
		sub: 'Temperatura (-1 frio a 1 quente): desloca R↔B.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'value',
				kind: 'literal',
				valueType: 'number',
				label: 'Value',
				default: 0,
				min: -1,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.texture',
		label: 'Textura',
		sub: 'Textura (aprox.): realça micro-detalhe (unsharp).',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'amount',
				kind: 'literal',
				valueType: 'number',
				label: 'Amount',
				default: 0.25,
				min: -1,
				max: 1,
				step: 0.01,
			},
			{
				name: 'radius',
				kind: 'literal',
				valueType: 'number',
				label: 'Radius',
				default: 1.2,
				min: 0.5,
				max: 6,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.threshold',
		label: 'Limiar',
		sub: 'Limiar (0..255): binariza P&B no ponto de corte.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.tint',
		label: 'Tonalidade',
		sub: 'Tonalidade (-1 verde a 1 magenta): desloca o canal verde.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'value',
				kind: 'literal',
				valueType: 'number',
				label: 'Value',
				default: 0,
				min: -1,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.toneCurve',
		label: 'Curva de Tons',
		sub: 'Curva tonal: S de contraste (s) + deslocamento do meio (m).',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 's',
				kind: 'literal',
				valueType: 'number',
				label: 'S',
				default: 0,
				min: -1,
				max: 1,
				step: 0.01,
			},
			{
				name: 'm',
				kind: 'literal',
				valueType: 'number',
				label: 'M',
				default: 0,
				min: -1,
				max: 1,
				step: 0.01,
			},
			{
				name: 'strength',
				kind: 'literal',
				valueType: 'number',
				label: 'Strength',
				default: 1,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'adjust.vibrance',
		label: 'Vibração',
		sub: 'Vibração (-1 a 1): satura mais as cores menos saturadas.',
		icon: 'sliders-horizontal',
		accent: 'emerald',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'value',
				kind: 'literal',
				valueType: 'number',
				label: 'Value',
				default: 0,
				min: -1,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'ai.backgroundRemoval',
		label: 'Remover Fundo (IA)',
		sub: 'Remove o fundo deixando o objeto sobre fundo branco (IA — Ge',
		icon: 'bot',
		accent: 'pink',
		category: 'ai',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'ai.colorize',
		label: 'Colorir Foto (IA)',
		sub: 'Coloriza foto P&B com cores realistas e naturais (IA — Gemin',
		icon: 'bot',
		accent: 'pink',
		category: 'ai',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'ai.restoration',
		label: 'Restaurar Foto (IA)',
		sub: 'Restaura foto antiga/danificada: remove riscos/ruído e recup',
		icon: 'bot',
		accent: 'pink',
		category: 'ai',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'blur.box',
		label: 'Desfoque Box',
		sub: 'Desfoque box (aprox. ≈ gaussiano via sharp.blur).',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'radius',
				kind: 'literal',
				valueType: 'number',
				label: 'Radius',
				default: 3,
				min: 1,
				max: 50,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'blur.gaussian',
		label: 'Desfoque Gaussiano',
		sub: 'Desfoque gaussiano (sigma).',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'sigma',
				kind: 'literal',
				valueType: 'number',
				label: 'Sigma',
				default: 3,
				min: 0.3,
				max: 50,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'blur.motion',
		label: 'Desfoque de Movimento',
		sub: 'Desfoque de movimento: convolução com linha no ângulo (distâ',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'angle',
				kind: 'literal',
				valueType: 'number',
				label: 'Angle',
				default: 0,
				min: 0,
				max: 360,
				step: 1,
			},
			{
				name: 'distance',
				kind: 'literal',
				valueType: 'number',
				label: 'Distance',
				default: 20,
				min: 0,
				max: 100,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'blur.radial',
		label: 'Desfoque Radial',
		sub: 'Desfoque radial (aprox.): média de cópias escaladas a partir',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'strength',
				kind: 'literal',
				valueType: 'number',
				label: 'Strength',
				default: 0.3,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'centerX',
				kind: 'literal',
				valueType: 'number',
				label: 'Center X',
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'centerY',
				kind: 'literal',
				valueType: 'number',
				label: 'Center Y',
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'blur.surface',
		label: 'Desfoque de Superfície',
		sub: 'Desfoque de superfície (aprox. bilateral via filtro de media',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'radius',
				kind: 'literal',
				valueType: 'number',
				label: 'Radius',
				default: 5,
				min: 0,
				max: 10,
				step: 1,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 0.2,
				min: 0.01,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'detail.denoise',
		label: 'Reduzir Ruído',
		sub: 'Redução de ruído (aprox.): filtro de mediana proporcional.',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'strength',
				kind: 'literal',
				valueType: 'number',
				label: 'Strength',
				default: 1,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'detail.sharpen',
		label: 'Nitidez',
		sub: 'Nitidez por intensidade (0..2).',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'strength',
				kind: 'literal',
				valueType: 'number',
				label: 'Strength',
				default: 0.5,
				min: 0,
				max: 2,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'detail.unsharpMask',
		label: 'Máscara de Nitidez',
		sub: 'Máscara de nitidez (unsharp) padrão.',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.atkinson',
		label: 'Dither Atkinson',
		sub: 'Atkinson: alto contraste, ótimo p/ laser (difunde 75% do err',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.bayer4',
		label: 'Dither Bayer 4×4',
		sub: 'Bayer 4×4: ordered dithering compacto (ignora threshold).',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.bayer8',
		label: 'Dither Bayer 8×8',
		sub: 'Bayer 8×8: ordered dithering estruturado (ignora threshold).',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.blueNoise',
		label: 'Dither Blue Noise',
		sub: 'Blue-noise (aprox.): limiar por ruído pseudo-aleatório deter',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'strength',
				kind: 'literal',
				valueType: 'number',
				label: 'Strength',
				default: 1,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.burkes',
		label: 'Dither Burkes',
		sub: 'Burkes: difusão de erro em 2 linhas (divisor 32).',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.errorDiffusion',
		label: 'Dither Multinível',
		sub: 'Difusão de erro multinível: Floyd-Steinberg quantizando em N',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'levels',
				kind: 'literal',
				valueType: 'int',
				label: 'Levels',
				default: 2,
				min: 2,
				max: 8,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.floydSteinberg',
		label: 'Dither Floyd–Steinberg',
		sub: 'Floyd-Steinberg: difusão de erro padrão (4 vizinhos).',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.halftone',
		label: 'Meio-tom',
		sub: 'Halftone: pontos tipo jornal (matriz radial, ignora threshol',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.jarvis',
		label: 'Dither Jarvis',
		sub: 'Jarvis-Judice-Ninke: kernel largo, gradientes suaves.',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.sierra',
		label: 'Dither Sierra',
		sub: 'Sierra (full): bom equilíbrio qualidade/velocidade.',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.sierra2',
		label: 'Dither Sierra-2',
		sub: 'Sierra-2-row: difusão de erro em 2 linhas (divisor 16).',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.sierraLite',
		label: 'Dither Sierra Lite',
		sub: 'Sierra-Lite: difusão de erro mínima (divisor 4, rápido).',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'dither.stucki',
		label: 'Dither Stucki',
		sub: 'Stucki: alta qualidade p/ fotos (12 vizinhos).',
		icon: 'grid-2x2',
		accent: 'zinc',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'edge.canny',
		label: 'Bordas Canny',
		sub: 'Canny (aprox.): blur gaussiano + Sobel + duplo limiar (histe',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'strength',
				kind: 'literal',
				valueType: 'number',
				label: 'Strength',
				default: 1,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'low',
				kind: 'literal',
				valueType: 'number',
				label: 'Low',
				default: 0.12,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'high',
				kind: 'literal',
				valueType: 'number',
				label: 'High',
				default: 0.28,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'blur',
				kind: 'literal',
				valueType: 'number',
				label: 'Blur',
				default: 0.35,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'invert',
				kind: 'literal',
				valueType: 'bool',
				label: 'Invert',
				default: false,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'edge.edgeDetect',
		label: 'Detectar Bordas',
		sub: 'Detecção de bordas: Sobel normalizado + limiar, intensidade ',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'strength',
				kind: 'literal',
				valueType: 'number',
				label: 'Strength',
				default: 1,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 0.2,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'invert',
				kind: 'literal',
				valueType: 'bool',
				label: 'Invert',
				default: false,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'edge.highPass',
		label: 'Passa-Alta',
		sub: 'Passa-alta: original − blur gaussiano (5×5), recentrado em 1',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'edge.outline',
		label: 'Contorno',
		sub: 'Contorno: kernel laplaciano 3×3 [-1…8…-1] (realça bordas).',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'edge.sobel',
		label: 'Bordas Sobel',
		sub: 'Bordas Sobel: magnitude do gradiente (sqrt(gx²+gy²)) sobre o',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'fx.emboss',
		label: 'Relevo',
		sub: 'Relevo direcional: convolução emboss + bias 128, misturado c',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'blend',
				kind: 'literal',
				valueType: 'number',
				label: 'Blend',
				default: 1,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'amount',
				kind: 'literal',
				valueType: 'number',
				label: 'Amount',
				default: 3,
				min: 0,
				max: 8,
				step: 1,
			},
			{
				name: 'angle',
				kind: 'literal',
				valueType: 'number',
				label: 'Angle',
				default: 0.785,
				min: 0,
				max: 6.28,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'fx.filmGrain',
		label: 'Granulado de Filme',
		sub: 'Grão de filme (aprox.): ruído mono sutil modulado pela lumin',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'amount',
				kind: 'literal',
				valueType: 'number',
				label: 'Amount',
				default: 0.08,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'fx.invert',
		label: 'Inverter Cores',
		sub: 'Inverte as cores (negativo), preservando o alpha.',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'fx.lensDistortion',
		label: 'Distorção de Lente',
		sub: 'Distorção de lente: barril (>0) / almofada (<0) via remap ra',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'amount',
				kind: 'literal',
				valueType: 'number',
				label: 'Amount',
				default: 0.2,
				min: -0.5,
				max: 0.5,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'fx.morphology',
		label: 'Morfologia',
		sub: 'Morfologia: erosão (min) ou dilatação (max) num raio quadrad',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'op',
				kind: 'literal',
				valueType: 'enum',
				label: 'Op',
				default: 'dilate',
				options: ['erode', 'dilate'],
			},
			{
				name: 'radius',
				kind: 'literal',
				valueType: 'int',
				label: 'Radius',
				default: 1,
				min: 1,
				max: 5,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'fx.noise',
		label: 'Ruído',
		sub: 'Ruído mono (aprox.): adiciona ±amount·255 determinístico por',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'amount',
				kind: 'literal',
				valueType: 'number',
				label: 'Amount',
				default: 0.2,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'geo.addText',
		label: 'Adicionar Texto',
		sub: 'Compõe um texto sobre a imagem na posição x,y (% do tamanho)',
		icon: 'frame',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'text',
				kind: 'literal',
				valueType: 'string',
				label: 'Text',
				default: 'Texto',
			},
			{
				name: 'size',
				kind: 'literal',
				valueType: 'int',
				label: 'Size',
				default: 48,
				min: 8,
				max: 200,
				step: 1,
			},
			{
				name: 'color',
				kind: 'literal',
				valueType: 'string',
				label: 'Color',
				default: '#000000',
			},
			{
				name: 'x',
				kind: 'literal',
				valueType: 'number',
				label: 'X',
				default: 50,
				min: 0,
				max: 100,
				step: 1,
			},
			{
				name: 'y',
				kind: 'literal',
				valueType: 'number',
				label: 'Y',
				default: 50,
				min: 0,
				max: 100,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'geo.border',
		label: 'Borda',
		sub: 'Adiciona uma moldura sólida de N pixels ao redor.',
		icon: 'frame',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'size',
				kind: 'literal',
				valueType: 'int',
				label: 'Size',
				default: 20,
				min: 0,
				max: 200,
				step: 1,
			},
			{
				name: 'color',
				kind: 'literal',
				valueType: 'string',
				label: 'Color',
				default: '#000000',
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'geo.crop',
		label: 'Recortar',
		sub: 'Recorte por porcentagem do tamanho (x,y = canto; w,h = taman',
		icon: 'frame',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'xPct',
				kind: 'literal',
				valueType: 'number',
				label: 'X Pct',
				default: 0,
				min: 0,
				max: 100,
				step: 1,
			},
			{
				name: 'yPct',
				kind: 'literal',
				valueType: 'number',
				label: 'Y Pct',
				default: 0,
				min: 0,
				max: 100,
				step: 1,
			},
			{
				name: 'wPct',
				kind: 'literal',
				valueType: 'number',
				label: 'W Pct',
				default: 100,
				min: 1,
				max: 100,
				step: 1,
			},
			{
				name: 'hPct',
				kind: 'literal',
				valueType: 'number',
				label: 'H Pct',
				default: 100,
				min: 1,
				max: 100,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'geo.edgeFade',
		label: 'Bordas Esmaecidas',
		sub: 'Desvanece as bordas pra transparente (vinheta no canal alpha',
		icon: 'frame',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'size',
				kind: 'literal',
				valueType: 'int',
				label: 'Size',
				default: 40,
				min: 0,
				max: 200,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'geo.flip',
		label: 'Espelhar',
		sub: 'Espelha horizontal (flop) e/ou vertical (flip).',
		icon: 'frame',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'horizontal',
				kind: 'literal',
				valueType: 'bool',
				label: 'Horizontal',
				default: true,
			},
			{
				name: 'vertical',
				kind: 'literal',
				valueType: 'bool',
				label: 'Vertical',
				default: false,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'geo.perspective',
		label: 'Perspectiva',
		sub: 'Perspectiva (aprox.): cisalhamento via affine simulando incl',
		icon: 'frame',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'horizontal',
				kind: 'literal',
				valueType: 'number',
				label: 'Horizontal',
				default: 0,
				min: -0.4,
				max: 0.4,
				step: 0.01,
			},
			{
				name: 'vertical',
				kind: 'literal',
				valueType: 'number',
				label: 'Vertical',
				default: 0,
				min: -0.4,
				max: 0.4,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'geo.resize',
		label: 'Redimensionar',
		sub: 'Redimensiona pra uma largura (mantendo proporção ou quadrado',
		icon: 'frame',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'width',
				kind: 'literal',
				valueType: 'int',
				label: 'Width',
				default: 800,
				min: 1,
				max: 8000,
				step: 1,
			},
			{
				name: 'keepAspect',
				kind: 'literal',
				valueType: 'bool',
				label: 'Keep Aspect',
				default: true,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'geo.rotate',
		label: 'Girar',
		sub: 'Rotaciona (-180 a 180 graus) preenchendo o fundo com a cor d',
		icon: 'frame',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'angle',
				kind: 'literal',
				valueType: 'number',
				label: 'Angle',
				default: 0,
				min: -180,
				max: 180,
				step: 1,
			},
			{
				name: 'bg',
				kind: 'literal',
				valueType: 'string',
				label: 'Bg',
				default: '#ffffff',
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'geo.scale',
		label: 'Escalar',
		sub: 'Escala por fator (0.1 a 4): multiplica largura e altura.',
		icon: 'frame',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'factor',
				kind: 'literal',
				valueType: 'number',
				label: 'Factor',
				default: 1,
				min: 0.1,
				max: 4,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'geo.skew',
		label: 'Inclinar',
		sub: 'Cisalhamento (skew) em X e Y via transformação afim.',
		icon: 'frame',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'skewX',
				kind: 'literal',
				valueType: 'number',
				label: 'Skew X',
				default: 0,
				min: -0.5,
				max: 0.5,
				step: 0.01,
			},
			{
				name: 'skewY',
				kind: 'literal',
				valueType: 'number',
				label: 'Skew Y',
				default: 0,
				min: -0.5,
				max: 0.5,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'geo.tile',
		label: 'Ladrilhar',
		sub: 'Repete a imagem numa grade cols×rows (mantém o tamanho origi',
		icon: 'frame',
		accent: 'sky',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'cols',
				kind: 'literal',
				valueType: 'int',
				label: 'Cols',
				default: 2,
				min: 1,
				max: 10,
				step: 1,
			},
			{
				name: 'rows',
				kind: 'literal',
				valueType: 'int',
				label: 'Rows',
				default: 2,
				min: 1,
				max: 10,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'image.upscale',
		label: 'Ampliar Imagem',
		sub: 'Amplia 2/4/8/16× com reamostragem Lanczos3 (não é IA).',
		icon: 'bot',
		accent: 'pink',
		category: 'ai',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'factor',
				kind: 'literal',
				valueType: 'enum',
				label: 'Factor',
				default: '2',
				options: ['2', '4', '8', '16'],
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'laser.crystalEngraving',
		label: 'Gravação em Cristal 3D',
		sub: 'Gravação em cristal: prévia do mapa de profundidade (graysca',
		icon: 'flame',
		accent: 'orange',
		category: 'laser',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'depthLevels',
				kind: 'literal',
				valueType: 'int',
				label: 'Depth Levels',
				default: 8,
				min: 2,
				max: 16,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'laser.materialPreset',
		label: 'Preset por Material',
		sub: 'Preset de material: aplica uma curva tonal nomeada + graysca',
		icon: 'flame',
		accent: 'orange',
		category: 'laser',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'material',
				kind: 'literal',
				valueType: 'enum',
				label: 'Material',
				default: 'wood',
				options: [
					'wood',
					'black slate',
					'glass',
					'acrylic',
					'leather',
					'cork',
					'andonized aluminum',
					'stainless steel',
					'white tile',
					'white tile painted black',
				],
			},
			{
				name: 'algorithm',
				kind: 'literal',
				valueType: 'enum',
				label: 'Algorithm',
				default: 'norton',
				options: [
					'old',
					'norton',
					'co2',
					'co2v2',
					'baning',
					'marcin',
					'sketch',
					'nero',
					'kasia',
					'skeldon',
				],
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'laser.oneClick',
		label: 'Gravação 1-Clique',
		sub: 'Gravação 1-Clique: preparo completo (tom por material + resi',
		icon: 'flame',
		accent: 'orange',
		category: 'laser',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'material',
				kind: 'literal',
				valueType: 'enum',
				label: 'Material',
				default: 'wood',
				options: [
					'wood',
					'black slate',
					'glass',
					'acrylic',
					'leather',
					'cork',
					'andonized aluminum',
					'stainless steel',
					'white tile',
					'white tile painted black',
				],
			},
			{
				name: 'width_mm',
				kind: 'literal',
				valueType: 'number',
				label: 'Width Mm',
				default: 100,
				min: 1,
				max: 2000,
				step: 1,
			},
			{
				name: 'dpi',
				kind: 'literal',
				valueType: 'int',
				label: 'Dpi',
				default: 254,
				step: 1,
			},
			{
				name: 'noDither',
				kind: 'literal',
				valueType: 'bool',
				label: 'No Dither',
				default: false,
			},
			{
				name: 'cleanBackground',
				kind: 'literal',
				valueType: 'bool',
				label: 'Clean Background',
				default: false,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'laser.oneTouch',
		label: 'Ajuste Rápido',
		sub: 'One-Touch: toggles rápidos (gama / remover ruído / nitidez) ',
		icon: 'flame',
		accent: 'orange',
		category: 'laser',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'gamma',
				kind: 'literal',
				valueType: 'bool',
				label: 'Gamma',
				default: false,
			},
			{
				name: 'denoise',
				kind: 'literal',
				valueType: 'bool',
				label: 'Denoise',
				default: false,
			},
			{
				name: 'sharpen',
				kind: 'literal',
				valueType: 'bool',
				label: 'Sharpen',
				default: false,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'mask.alphaFeather',
		label: 'Suavizar Borda',
		sub: 'Suaviza a borda do alpha (aprox.): desfoque box só no canal ',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'radius',
				kind: 'literal',
				valueType: 'number',
				label: 'Radius',
				default: 2,
				min: 0,
				max: 24,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'mask.alphaThreshold',
		label: 'Limiar de Transparência',
		sub: 'Limiar de alpha: binariza o canal alpha com transição suave ',
		icon: 'wand-2',
		accent: 'violet',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'softness',
				kind: 'literal',
				valueType: 'number',
				label: 'Softness',
				default: 0.02,
				min: 0,
				max: 0.5,
				step: 0.01,
			},
			{
				name: 'invert',
				kind: 'literal',
				valueType: 'bool',
				label: 'Invert',
				default: false,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.bloom',
		label: 'Brilho Suave',
		sub: 'Bloom: bright-pass + blur gaussiano somado de volta (screen)',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'number',
				label: 'Threshold',
				default: 0.75,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'radius',
				kind: 'literal',
				valueType: 'number',
				label: 'Radius',
				default: 6,
				min: 0.5,
				max: 20,
				step: 1,
			},
			{
				name: 'intensity',
				kind: 'literal',
				valueType: 'number',
				label: 'Intensity',
				default: 1.5,
				min: 0,
				max: 8,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.comic',
		label: 'Quadrinhos',
		sub: 'HQ: posteriza + sobrepõe contornos pretos (edge laplaciano).',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'levels',
				kind: 'literal',
				valueType: 'int',
				label: 'Levels',
				default: 4,
				min: 2,
				max: 6,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.crossProcess',
		label: 'Cross Process',
		sub: 'Cross-process: curvas por canal (boost R/G, sombras B levant',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'intensity',
				kind: 'literal',
				valueType: 'number',
				label: 'Intensity',
				default: 1,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.duotone',
		label: 'Duotone',
		sub: 'Duotone: mapa de gradiente entre 2 cores por luminância, ble',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'shadowColor',
				kind: 'literal',
				valueType: 'string',
				label: 'Shadow Color',
				default: '#1a1a2e',
			},
			{
				name: 'highlightColor',
				kind: 'literal',
				valueType: 'string',
				label: 'Highlight Color',
				default: '#e94560',
			},
			{
				name: 'intensity',
				kind: 'literal',
				valueType: 'number',
				label: 'Intensity',
				default: 1,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.glitch',
		label: 'Glitch',
		sub: 'Glitch: desloca canais R/B na horizontal + faixas deslocadas',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'intensity',
				kind: 'literal',
				valueType: 'number',
				label: 'Intensity',
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'rgbShift',
				kind: 'literal',
				valueType: 'number',
				label: 'Rgb Shift',
				default: 5,
				min: 0,
				max: 20,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.halftone',
		label: 'Pontos de Jornal',
		sub: 'Halftone: pontos tipo jornal — ponto por célula proporcional',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'cell',
				kind: 'literal',
				valueType: 'number',
				label: 'Cell',
				default: 14,
				min: 2,
				max: 120,
				step: 1,
			},
			{
				name: 'angle',
				kind: 'literal',
				valueType: 'number',
				label: 'Angle',
				default: 0,
				min: -3.14,
				max: 3.14,
				step: 0.01,
			},
			{
				name: 'contrast',
				kind: 'literal',
				valueType: 'number',
				label: 'Contrast',
				default: 1.5,
				min: 0.25,
				max: 4,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.lightLeak',
		label: 'Vazamento de Luz',
		sub: 'Light leak: gradiente de luz colorido num canto, composto em',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'intensity',
				kind: 'literal',
				valueType: 'number',
				label: 'Intensity',
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'color',
				kind: 'literal',
				valueType: 'string',
				label: 'Color',
				default: '#ff7b00',
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.oilPaint',
		label: 'Pintura a Óleo',
		sub: 'Pintura a óleo (aprox.): mediana (sharp) + leve posterização',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'radius',
				kind: 'literal',
				valueType: 'number',
				label: 'Radius',
				default: 4,
				min: 1,
				max: 8,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.pixelate',
		label: 'Pixelizar',
		sub: 'Pixelate: downscale + upscale nearest (blocos quadrados).',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'pixelSize',
				kind: 'literal',
				valueType: 'number',
				label: 'Pixel Size',
				default: 8,
				min: 1,
				max: 100,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.sepia',
		label: 'Sépia',
		sub: 'Sépia: recombinação clássica, blend com o original por inten',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'intensity',
				kind: 'literal',
				valueType: 'number',
				label: 'Intensity',
				default: 1,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.sketch',
		label: 'Desenho a Lápis',
		sub: 'Esboço a lápis: gray dodge invert(blur(gray)) — out=gray*255',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'blurRadius',
				kind: 'literal',
				valueType: 'number',
				label: 'Blur Radius',
				default: 6,
				min: 2,
				max: 15,
				step: 1,
			},
			{
				name: 'darkness',
				kind: 'literal',
				valueType: 'number',
				label: 'Darkness',
				default: 1,
				min: 0.5,
				max: 2,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.splitToning',
		label: 'Split Toning',
		sub: 'Split-toning: tinge sombras e luzes com cores distintas conf',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'shadowColor',
				kind: 'literal',
				valueType: 'string',
				label: 'Shadow Color',
				default: '#26408b',
			},
			{
				name: 'highlightColor',
				kind: 'literal',
				valueType: 'string',
				label: 'Highlight Color',
				default: '#f2d680',
			},
			{
				name: 'balance',
				kind: 'literal',
				valueType: 'number',
				label: 'Balance',
				default: 0,
				min: -1,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.stipple',
		label: 'Pontilhismo',
		sub: 'Pontilhismo P&B: pontos pretos com probabilidade ~ (1-luma) ',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'density',
				kind: 'literal',
				valueType: 'number',
				label: 'Density',
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'stylize.vignette',
		label: 'Vinheta',
		sub: 'Vinheta: escurece (ou clareia se amount<0) as bordas radialm',
		icon: 'sparkles',
		accent: 'fuchsia',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'amount',
				kind: 'literal',
				valueType: 'number',
				label: 'Amount',
				default: 0.55,
				min: -1,
				max: 1,
				step: 0.01,
			},
			{
				name: 'radius',
				kind: 'literal',
				valueType: 'number',
				label: 'Radius',
				default: 0.65,
				min: 0.05,
				max: 1.2,
				step: 0.01,
			},
			{
				name: 'feather',
				kind: 'literal',
				valueType: 'number',
				label: 'Feather',
				default: 0.35,
				min: 0.001,
				max: 1,
				step: 0.01,
			},
			{
				name: 'centerX',
				kind: 'literal',
				valueType: 'number',
				label: 'Center X',
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.01,
			},
			{
				name: 'centerY',
				kind: 'literal',
				valueType: 'number',
				label: 'Center Y',
				default: 0.5,
				min: 0,
				max: 1,
				step: 0.01,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'util.dpiTest',
		label: 'Teste de DPI',
		sub: 'Cartão de teste de DPI: gera uma régua/grade de 25,4 mm e ra',
		icon: 'flame',
		accent: 'orange',
		category: 'util',
		params: [
			{
				name: 'dpi',
				kind: 'literal',
				valueType: 'int',
				label: 'Dpi',
				default: 254,
				min: 72,
				max: 1200,
				step: 1,
			},
		],
		outputs: [
			{
				name: 'png',
				type: 'buffer',
				label: 'PNG',
			},
			{
				name: 'pngBase64',
				type: 'string',
				label: 'base64',
			},
		],
	},
	{
		id: 'vector.contour',
		label: 'Contorno Vetorial',
		sub: 'Contorno vetorial: traça o limiar como linha (stroke) e devo',
		icon: 'pen-line',
		accent: 'cyan',
		category: 'image',
		params: [
			{
				name: 'image',
				kind: 'ref',
				refType: 'buffer',
				label: 'Imagem',
				required: true,
			},
			{
				name: 'threshold',
				kind: 'literal',
				valueType: 'int',
				label: 'Threshold',
				default: 128,
				min: 0,
				max: 255,
				step: 1,
			},
			{
				name: 'color',
				kind: 'literal',
				valueType: 'string',
				label: 'Color',
				default: '#000000',
			},
		],
		outputs: [
			{
				name: 'svg',
				type: 'string',
				label: 'SVG',
			},
		],
	},
];
